### ISSUE TITLE
Entity velocity

### ISSUE THREAD

**Issue by ghost** [DarkStorm652/DarkBot#27] opened 2014-09-03 22:15 UTC
The bot entity will not handle velocity packets

**Comment by t81lal** [comment] 2014-09-06 17:45
i realised this quite a while ago and i wasn't sure what was up with it but i dont think it actually has to handle the velocity since the movement changes are so small that nocheat cant really know where exactly the server and client are synced to in the world. post more detail if you have an explicit problem such as anticheat actually rekking u because of this.

**Comment by LefsFlare** [comment] 2014-12-13 15:17
There's no velocity handling in the bot. It was not coded in.

**Comment by DarkStorm652** [comment] 2014-12-13 20:32
Duplicate of #26

**Closed as completed by DarkStorm652** 2014-12-13 20:32 UTC
